from __future__ import annotations

from types import MappingProxyType

from .models import (
    HostRole,
    JobSpec,
    JobState,
    LockScope,
    OutputPolicy,
    RetryPolicy,
    TriggerKind,
    TriggerSpec,
    WriterScope,
)
from .scheduler import EXPECTED_JOB_DEPLOYMENTS, validate_job_catalog


def _interval(seconds: int, *, run_at_load: bool = False) -> TriggerSpec:
    return TriggerSpec(
        kind=TriggerKind.INTERVAL,
        interval_seconds=seconds,
        run_at_load=run_at_load,
    )


def _calendar(hour: int, minute: int, *, weekday: int | None = None) -> TriggerSpec:
    return TriggerSpec(
        kind=TriggerKind.CALENDAR,
        hour=hour,
        minute=minute,
        weekday=weekday,
    )


def _keepalive() -> TriggerSpec:
    return TriggerSpec(kind=TriggerKind.KEEPALIVE, run_at_load=True)


def _calendar_interval(seconds: int) -> TriggerSpec:
    return TriggerSpec(
        kind=TriggerKind.CALENDAR_INTERVAL,
        interval_seconds=seconds,
        persistent=True,
    )


def _job(
    number: int,
    command: tuple[str, ...],
    *,
    host_role: HostRole,
    trigger: TriggerSpec,
    writer_scope: WriterScope,
    lock_scope: LockScope,
    timeout_seconds: int,
    retry: RetryPolicy = RetryPolicy.NEVER,
    env_refs: tuple[str, ...] = (),
    output_policy: OutputPolicy = OutputPolicy.METADATA_ONLY,
    state: JobState = JobState.ENABLED,
) -> JobSpec:
    job_id = f"JOB-{number:03d}"
    deployment_target, allowed_platforms = EXPECTED_JOB_DEPLOYMENTS[job_id]
    return JobSpec(
        id=job_id,
        command=command,
        deployment_target=deployment_target,
        allowed_platforms=allowed_platforms,
        host_role=host_role,
        trigger=trigger,
        writer_scope=writer_scope,
        lock_scope=lock_scope,
        timeout_seconds=timeout_seconds,
        retry=retry,
        env_refs=env_refs,
        output_policy=output_policy,
        state=state,
    )


JOB_CATALOG = validate_job_catalog(
    (
        _job(
            1,
            ("open-brain", "doctor", "--json", "--role=probe"),
            host_role=HostRole.PROBE,
            trigger=_interval(3600),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=300,
        ),
        _job(
            2,
            ("open-brain", "index", "--check", "--read-only", "--json"),
            host_role=HostRole.PROBE,
            trigger=_interval(7200, run_at_load=True),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=900,
        ),
        _job(
            3,
            ("open-brain", "now", "check", "--read-only", "--json"),
            host_role=HostRole.PROBE,
            trigger=_interval(300, run_at_load=True),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=300,
        ),
        _job(
            4,
            (
                "open-brain",
                "backup",
                "sqlite",
                "--profile=local",
                "--dry-run",
                "--json",
            ),
            host_role=HostRole.PROBE,
            trigger=_interval(3600, run_at_load=True),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=1800,
            env_refs=("OPEN_BRAIN_CONFIG",),
        ),
        _job(
            5,
            ("open-brain", "capture", "imessage-ingress", "--append", "--json"),
            host_role=HostRole.INGRESS,
            trigger=_keepalive(),
            writer_scope=WriterScope.CAPTURE_INGRESS,
            lock_scope=LockScope.INGRESS,
            timeout_seconds=300,
            retry=RetryPolicy.ON_FAILURE,
            env_refs=("OPEN_BRAIN_CONFIG", "OPEN_BRAIN_IMESSAGE_CONFIG"),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            6,
            ("open-brain", "close-day", "prepare", "--json", "--dry-run"),
            host_role=HostRole.PROBE,
            trigger=_calendar(8, 35),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=300,
            output_policy=OutputPolicy.REDACTED_REPORT,
            state=JobState.MANUAL,
        ),
        _job(
            7,
            ("open-brain", "dev", "signals", "scan", "--append-only", "--json"),
            host_role=HostRole.INGRESS,
            trigger=_calendar(3, 0),
            writer_scope=WriterScope.CAPTURE_INGRESS,
            lock_scope=LockScope.INGRESS,
            timeout_seconds=900,
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            8,
            ("open-brain", "lint", "--scope=work", "--write-report", "--json"),
            host_role=HostRole.PROBE,
            trigger=_calendar(4, 0, weekday=1),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=900,
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            9,
            ("open-brain", "hooks", "sync", "--dry-run", "--json"),
            host_role=HostRole.PROBE,
            trigger=_calendar(2, 55),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=300,
            output_policy=OutputPolicy.REDACTED_REPORT,
            state=JobState.MANUAL,
        ),
        _job(
            10,
            ("open-brain", "ledger", "run", "--nightly", "--json"),
            host_role=HostRole.WRITER,
            trigger=_calendar(3, 37),
            writer_scope=WriterScope.CONTENT,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=7200,
            env_refs=("OPEN_BRAIN_PROVIDER_CONFIG",),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            11,
            ("open-brain", "backup", "run", "--profile=capture", "--json"),
            host_role=HostRole.WRITER,
            trigger=_calendar(4, 15),
            writer_scope=WriterScope.BACKUP,
            lock_scope=LockScope.BACKUP_PROFILE,
            timeout_seconds=7200,
            env_refs=("OPEN_BRAIN_CONFIG",),
        ),
        _job(
            12,
            ("open-brain", "curation", "run", "--day=yesterday", "--json"),
            host_role=HostRole.WRITER,
            trigger=_calendar(2, 45),
            writer_scope=WriterScope.CONTENT,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=3600,
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            13,
            ("open-brain", "doctor", "--json", "--role=writer"),
            host_role=HostRole.PROBE,
            trigger=_interval(3600),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=300,
        ),
        _job(
            14,
            ("open-brain", "backup", "run", "--profile=full", "--json"),
            host_role=HostRole.WRITER,
            trigger=_calendar(3, 45),
            writer_scope=WriterScope.BACKUP,
            lock_scope=LockScope.BACKUP_PROFILE,
            timeout_seconds=10_800,
            env_refs=("OPEN_BRAIN_CONFIG",),
        ),
        _job(
            15,
            ("open-brain", "ops", "git-sync", "--json"),
            host_role=HostRole.WRITER,
            trigger=_interval(900, run_at_load=True),
            writer_scope=WriterScope.CONTENT,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=900,
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            16,
            ("open-brain", "index", "--scope=all", "--json"),
            host_role=HostRole.WRITER,
            trigger=_interval(7200, run_at_load=True),
            writer_scope=WriterScope.INDEX,
            lock_scope=LockScope.INDEX,
            timeout_seconds=3600,
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            17,
            (
                "open-brain",
                "lifeos",
                "nudge",
                "midday",
                "--date=CONFIGURED_DATE",
                "--json",
            ),
            host_role=HostRole.WRITER,
            trigger=_calendar(12, 0),
            writer_scope=WriterScope.STATE,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=300,
            env_refs=("OPEN_BRAIN_LIFEOS_CONFIG",),
        ),
        _job(
            18,
            (
                "open-brain",
                "lifeos",
                "plan",
                "--date=CONFIGURED_DATE",
                "--generic-titles",
                "--json",
            ),
            host_role=HostRole.WRITER,
            trigger=_calendar(6, 30),
            writer_scope=WriterScope.STATE,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=900,
            env_refs=("OPEN_BRAIN_LIFEOS_CONFIG",),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            19,
            (
                "open-brain",
                "lifeos",
                "reset",
                "--date=CONFIGURED_DATE",
                "--json",
            ),
            host_role=HostRole.WRITER,
            trigger=_calendar(21, 0),
            writer_scope=WriterScope.STATE,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=900,
            env_refs=("OPEN_BRAIN_LIFEOS_CONFIG",),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            20,
            ("open-brain", "messages", "extract", "--json", "--review-actions"),
            host_role=HostRole.WRITER,
            trigger=_calendar(3, 15),
            writer_scope=WriterScope.CONTENT,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=1800,
            env_refs=("OPEN_BRAIN_MESSAGES_CONFIG",),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            21,
            ("open-brain", "messages", "sync", "--dry-run", "--json"),
            host_role=HostRole.WRITER,
            trigger=_interval(900, run_at_load=True),
            writer_scope=WriterScope.STATE,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=900,
            env_refs=("OPEN_BRAIN_MESSAGES_CONFIG",),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            22,
            ("open-brain", "now", "build", "--role=writer", "--json"),
            host_role=HostRole.WRITER,
            trigger=_interval(300, run_at_load=True),
            writer_scope=WriterScope.STATE,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=300,
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            23,
            ("open-brain", "backup", "run", "--profile=personal", "--json"),
            host_role=HostRole.WRITER,
            trigger=_calendar(2, 30),
            writer_scope=WriterScope.BACKUP,
            lock_scope=LockScope.BACKUP_PROFILE,
            timeout_seconds=7200,
            env_refs=("OPEN_BRAIN_CONFIG",),
        ),
        _job(
            24,
            ("open-brain", "retention", "run", "--dry-run", "--json"),
            host_role=HostRole.WRITER,
            trigger=_calendar(5, 0),
            writer_scope=WriterScope.STATE,
            lock_scope=LockScope.SHARED_WRITER,
            timeout_seconds=3600,
            env_refs=("OPEN_BRAIN_RETENTION_CONFIG",),
            output_policy=OutputPolicy.REDACTED_REPORT,
            state=JobState.MANUAL,
        ),
        _job(
            25,
            ("open-brain", "backup", "run", "--profile=runtime-state", "--json"),
            host_role=HostRole.WRITER,
            trigger=_calendar(4, 35),
            writer_scope=WriterScope.BACKUP,
            lock_scope=LockScope.BACKUP_PROFILE,
            timeout_seconds=7200,
            env_refs=("OPEN_BRAIN_CONFIG",),
        ),
        _job(
            26,
            (
                "open-brain",
                "ui",
                "serve",
                "--bind=CONFIGURED_PRIVATE_BIND",
                "--port=CONFIGURED_PORT",
            ),
            host_role=HostRole.SERVICE,
            trigger=_keepalive(),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=300,
            retry=RetryPolicy.ON_FAILURE,
            env_refs=(
                "OPEN_BRAIN_CONFIG",
                "OPEN_BRAIN_UI_CONFIG",
                "OPEN_BRAIN_UI_TOKEN",
            ),
        ),
        _job(
            27,
            (
                "open-brain",
                "capture",
                "serve",
                "--bind=CONFIGURED_PRIVATE_BIND",
                "--port=CONFIGURED_PORT",
            ),
            host_role=HostRole.INGRESS,
            trigger=_keepalive(),
            writer_scope=WriterScope.CAPTURE_INGRESS,
            lock_scope=LockScope.INGRESS,
            timeout_seconds=300,
            retry=RetryPolicy.ON_FAILURE,
            env_refs=(
                "OPEN_BRAIN_CONFIG",
                "OPEN_BRAIN_INGRESS_CONFIG",
                "OPEN_BRAIN_INGRESS_TOKEN",
            ),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            28,
            (
                "open-brain",
                "capture",
                "serve",
                "--mode=ingress",
                "--bind=CONFIGURED_PRIVATE_BIND",
                "--port=CONFIGURED_PORT",
            ),
            host_role=HostRole.INGRESS,
            trigger=_keepalive(),
            writer_scope=WriterScope.CAPTURE_INGRESS,
            lock_scope=LockScope.INGRESS,
            timeout_seconds=300,
            retry=RetryPolicy.ON_FAILURE,
            env_refs=(
                "OPEN_BRAIN_CONFIG",
                "OPEN_BRAIN_INGRESS_CONFIG",
                "OPEN_BRAIN_INGRESS_TOKEN",
            ),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            29,
            (
                "open-brain",
                "capture",
                "poll",
                "--source=youtube",
                "--mode=ingress",
                "--json",
            ),
            host_role=HostRole.INGRESS,
            trigger=_calendar_interval(300),
            writer_scope=WriterScope.CAPTURE_INGRESS,
            lock_scope=LockScope.INGRESS,
            timeout_seconds=900,
            env_refs=("OPEN_BRAIN_YOUTUBE_CONFIG",),
            output_policy=OutputPolicy.REDACTED_REPORT,
        ),
        _job(
            30,
            ("open-brain", "now", "check", "--read-only", "--json"),
            host_role=HostRole.PROBE,
            trigger=_calendar_interval(300),
            writer_scope=WriterScope.NONE,
            lock_scope=LockScope.NONE,
            timeout_seconds=300,
        ),
    )
)

JOBS_BY_ID = MappingProxyType({job.id: job for job in JOB_CATALOG})


def get_job(job_id: str) -> JobSpec:
    try:
        return JOBS_BY_ID[job_id]
    except (KeyError, TypeError):
        raise KeyError("unknown operations job") from None
