"""Task-shaped local engine facade for the Phase 1 vertical slice."""

from open_brain.core.locks import LockScope
from open_brain.providers.base import ProviderMode

from .contracts import (
    CaptureReceipt,
    CaptureTask,
    Payload,
    PortabilityFault,
    PortabilityReceipt,
    PortabilityTask,
    RetrievalTask,
)
from .local import (
    BrainEngine,
    CaptureAction,
    CaptureFault,
    CaptureSubmission,
    CaptureSubmissionPath,
    DecisionOutcome,
    EngineTaskSet,
    EnrichmentProvider,
    EnrichmentRequest,
    EnrichmentUnavailable,
    EventPayload,
    FilePayload,
    InjectedFault,
    LocalEngineContext,
    MeasurementPayload,
    ProposalDraft,
    PublicJobCaptureContext,
    PublicJobCaptureSink,
    PublicProvenance,
    ReferencePayload,
    RetrievalResult,
    ScopedRetrieval,
    TextPayload,
    open_local_engine,
)

__all__ = [
    "BrainEngine",
    "CaptureAction",
    "CaptureFault",
    "CaptureReceipt",
    "CaptureSubmission",
    "CaptureSubmissionPath",
    "CaptureTask",
    "DecisionOutcome",
    "EnrichmentProvider",
    "EnrichmentRequest",
    "EnrichmentUnavailable",
    "EngineTaskSet",
    "EventPayload",
    "FilePayload",
    "InjectedFault",
    "LocalEngineContext",
    "LockScope",
    "MeasurementPayload",
    "Payload",
    "PortabilityFault",
    "PortabilityReceipt",
    "PortabilityTask",
    "ProposalDraft",
    "PublicJobCaptureContext",
    "PublicJobCaptureSink",
    "PublicProvenance",
    "ProviderMode",
    "ReferencePayload",
    "RetrievalResult",
    "RetrievalTask",
    "ScopedRetrieval",
    "TextPayload",
    "open_local_engine",
]
