"""Task-shaped local engine facade for the Phase 1 vertical slice."""

from open_brain.capture.models import (
    CapturePipeline,
    ExtractionFailure,
    ExtractionMetadata,
    ExtractionState,
    ExtractorKind,
    NormalizedExtraction,
    ShareRequest,
    ShareResponse,
    ShareStatus,
    TranscriptState,
)
from open_brain.core.ids import canonical_json_bytes, validate_identifier
from open_brain.core.locks import LockScope
from open_brain.core.models import (
    CaptureEnvelope,
    CaptureWhyOrigin,
    ContentKind,
    ContentOrigin,
    PrivacyDecision,
    PrivacyReason,
    Provenance,
    RawAssetRef,
    SourceType,
    ValidationError,
)
from open_brain.core.policy import classify_privacy
from open_brain.providers.base import ProviderMode

from .contracts import (
    CaptureReceipt,
    CaptureTask,
    InboxSpaceTask,
    Payload,
    Phase1TaskSet,
    PortabilityFault,
    PortabilityReceipt,
    PortabilityTask,
    RetrievalTask,
    ReviewTask,
    ScopedRetrievalTask,
    project_public_result_text,
    project_public_space,
)
from .local import (
    BrainEngine,
    CaptureAction,
    CaptureFault,
    CaptureSubmission,
    CaptureSubmissionPath,
    DecisionOutcome,
    EngineTaskSet,
    EnrichmentProvider,
    EnrichmentRequest,
    EnrichmentUnavailable,
    EventPayload,
    FilePayload,
    InjectedFault,
    LocalEngineContext,
    MeasurementPayload,
    ProposalDraft,
    PublicJobCaptureContext,
    PublicJobCaptureSink,
    PublicProvenance,
    ReferencePayload,
    RetrievalResult,
    ScopedRetrieval,
    TextPayload,
    open_local_engine,
)

__all__ = [
    "BrainEngine",
    "CaptureAction",
    "CaptureEnvelope",
    "CapturePipeline",
    "CaptureFault",
    "CaptureReceipt",
    "CaptureSubmission",
    "CaptureSubmissionPath",
    "CaptureTask",
    "CaptureWhyOrigin",
    "ContentKind",
    "ContentOrigin",
    "DecisionOutcome",
    "EnrichmentProvider",
    "EnrichmentRequest",
    "EnrichmentUnavailable",
    "EngineTaskSet",
    "ExtractionFailure",
    "ExtractionMetadata",
    "ExtractionState",
    "ExtractorKind",
    "EventPayload",
    "FilePayload",
    "InjectedFault",
    "InboxSpaceTask",
    "LocalEngineContext",
    "LockScope",
    "MeasurementPayload",
    "NormalizedExtraction",
    "Payload",
    "Phase1TaskSet",
    "PortabilityFault",
    "PortabilityReceipt",
    "PortabilityTask",
    "PrivacyDecision",
    "PrivacyReason",
    "ProposalDraft",
    "PublicJobCaptureContext",
    "PublicJobCaptureSink",
    "PublicProvenance",
    "Provenance",
    "ProviderMode",
    "ReferencePayload",
    "RawAssetRef",
    "RetrievalResult",
    "RetrievalTask",
    "ReviewTask",
    "ScopedRetrieval",
    "ScopedRetrievalTask",
    "ShareRequest",
    "ShareResponse",
    "ShareStatus",
    "SourceType",
    "TextPayload",
    "TranscriptState",
    "ValidationError",
    "canonical_json_bytes",
    "validate_identifier",
    "open_local_engine",
    "classify_privacy",
    "project_public_result_text",
    "project_public_space",
]
